# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import nucleai_pb2 as nucleai__pb2


class LearningStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Enqueue = channel.unary_unary(
        '/nucleai.Learning/Enqueue',
        request_serializer=nucleai__pb2.EnqueueRequest.SerializeToString,
        response_deserializer=nucleai__pb2.EnqueueResponse.FromString,
        )
    self.Download = channel.unary_unary(
        '/nucleai.Learning/Download',
        request_serializer=nucleai__pb2.DownloadRequest.SerializeToString,
        response_deserializer=nucleai__pb2.DownloadResponse.FromString,
        )
    self.Upload = channel.unary_unary(
        '/nucleai.Learning/Upload',
        request_serializer=nucleai__pb2.UploadRequest.SerializeToString,
        response_deserializer=nucleai__pb2.UploadResponse.FromString,
        )


class LearningServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Enqueue(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Download(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Upload(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_LearningServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Enqueue': grpc.unary_unary_rpc_method_handler(
          servicer.Enqueue,
          request_deserializer=nucleai__pb2.EnqueueRequest.FromString,
          response_serializer=nucleai__pb2.EnqueueResponse.SerializeToString,
      ),
      'Download': grpc.unary_unary_rpc_method_handler(
          servicer.Download,
          request_deserializer=nucleai__pb2.DownloadRequest.FromString,
          response_serializer=nucleai__pb2.DownloadResponse.SerializeToString,
      ),
      'Upload': grpc.unary_unary_rpc_method_handler(
          servicer.Upload,
          request_deserializer=nucleai__pb2.UploadRequest.FromString,
          response_serializer=nucleai__pb2.UploadResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'nucleai.Learning', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
